#!/bin/bash
./asm.sh src/nullFM
./asm.sh src/spi.msb
./asm.sh src/spi.msb.c2
./asm.sh src/spi.msb.l1
./asm.sh src/spi.msb.l1.c2
./asm.sh src/spi.msblsb
./asm.sh src/spi.msblsb.c2
./asm.sh src/spi.msblsb.l1
./asm.sh src/spi.msblsb.l1.c2
./asm.sh src/spi.msbxlsb
./asm.sh src/spi.msbxlsb.c2
./asm.sh src/spi.msbxlsb.l1
./asm.sh src/spi.msbxlsb.l1.c2
./asm.sh src/spibus.disto
./asm.sh src/spibus.slot3
./asm.sh src/spibus.disto.l1
./asm.sh src/spibus.slot3.l1
./asm.sh src/flash0_35s
./asm.sh src/w25qxx

